on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        ports: 
          - 3000:3000
        with:
          who-to-greet: 'Mona the Octocat'
          ip: '${{steps.ip.outputs.ipv4}}'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
